import type { NextPage } from 'next'
import Head from 'next/head'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'

import { i18nApply, i18nPageContext, useTranslation } from '@i18n'

const AboutMePage: NextPage = () => {
  const { t } = useTranslation()
  return (
    <>
      <Head>
        <title>Emanuel Casco | {t('meta.title')}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <article>
        <section id="introduction">ABOUT ME</section>
      </article>
    </>
  )
}

export async function getStaticProps(context: i18nPageContext) {
  return {
    props: {
      ...(await i18nApply(serverSideTranslations, context.locale, ['home'])),
    },
  }
}

export default AboutMePage
