import Head from 'next/head'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'

import StackContainer from '@components/UI/Containers/StackContainer'
import Heading from '@components/UI/Heading'
import PostsList from '@components/Posts/PostsList'
import { Post } from '@entities'
import { i18nApply, I18nPage, i18nPageContext } from '@i18n'
import { getAllPosts } from '@services/posts.service'

type BlogPageStatic = I18nPage<{
  posts: Post[]
}>

const BlogPage: BlogPageStatic = ({ posts }) => {
  return (
    <>
      <Head>
        <title>Emanuel Casco | Blog</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <StackContainer tag="article">
        <Heading type="h2">Blog.</Heading>
        <PostsList posts={posts} />
      </StackContainer>
    </>
  )
}

export async function getStaticProps(context: i18nPageContext) {
  const posts = getAllPosts(context.locale, {
    pagination: { limit: 50 },
  })

  return {
    props: {
      ...(await i18nApply(serverSideTranslations, context.locale, ['blog'])),
      posts,
    },
  }
}

export default BlogPage
