import Head from 'next/head'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'

import { i18nPageContext, i18nApply, I18nPage, useTranslation } from '@i18n'
import Heading from '@components/UI/Heading'
import PostsList from '@components/Posts/PostsList'
import Introduction from '@components/Introduction'
import AirDivider from '@components/UI/Dividers/AirDivider'
import FancyDivider from '@components/UI/Dividers/FancyDivider'
import { Post } from '@entities'
import { getAllPosts } from '@services/posts.service'
import StackContainer from '@components/UI/Containers/StackContainer'

type HomePageStaticProps = I18nPage<{
  posts: Post[]
}>

const Home: HomePageStaticProps = ({ posts }) => {
  const { t } = useTranslation('home')
  return (
    <>
      <Head>
        <title>Emanuel Casco | {t('meta.title')}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <StackContainer tag="article">
        <AirDivider />
        <Introduction />
        <FancyDivider />
        <StackContainer tag="section">
          <Heading type="h2">Blog.</Heading>
          <PostsList posts={posts} />
        </StackContainer>
      </StackContainer>
    </>
  )
}

export const getStaticProps = async (context: i18nPageContext) => {
  const posts = getAllPosts(context.locale, {
    pagination: { limit: 5 },
  })

  return {
    props: {
      ...(await i18nApply(serverSideTranslations, context.locale, ['home'])),
      posts,
    },
  }
}

export default Home
